/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerfilOperativoRouteImport } from './routes/perfil-operativo'
import { Route as IndexRouteImport } from './routes/index'

const PerfilOperativoRoute = PerfilOperativoRouteImport.update({
  id: '/perfil-operativo',
  path: '/perfil-operativo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/perfil-operativo': typeof PerfilOperativoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/perfil-operativo': typeof PerfilOperativoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/perfil-operativo': typeof PerfilOperativoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/perfil-operativo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/perfil-operativo'
  id: '__root__' | '/' | '/perfil-operativo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PerfilOperativoRoute: typeof PerfilOperativoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perfil-operativo': {
      id: '/perfil-operativo'
      path: '/perfil-operativo'
      fullPath: '/perfil-operativo'
      preLoaderRoute: typeof PerfilOperativoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PerfilOperativoRoute: PerfilOperativoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
